##########################################
#                 SIGN UP
##########################################
POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "ffffff",
  "passwordCheck": "ffffff",
  "userName": "Mr. USER"
}





##########################################
#                 LOG IN
##########################################
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
  "email": "mod@gmail.com",
  "password": "ffffff"  
}










##########################################
#             VERIFY  TOKEN
##########################################
POST http://localhost:5000/verifyToken HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmM2I0MWI1MGQ2ZjU5MWYyNGM5Njc4NiIsImlhdCI6MTU5NzcyNTcyMX0.yifVnPNxuHOrECHCaSmNCgl4eqExSHHJS1qHjyU1Nfg

